  
version: "3.7"

networks:
    TheJesusNetwork:
        driver: overlay

services:

    service_1:
        
        image:
            shana12345/microservice_1
        environment: 
           - MYSQL=${MYSQL}
            - MYSQLUSER=${MYSQLUSER}
            - MYSQLPASSWORD=${MYSQLPASSWORD}
            - MYSQLDB=${MYSQLDB}
        ports: 
            - "5000:5000"
        networks:
            - TheJesusNetwork
        deploy:
            replicas: 3

    service_2:
        
        image:
            shana12345/microservice_2
        ports: 
            - "5001:5001"
        networks:
            - TheJesusNetwork
        deploy:
            replicas: 3

    service_3:
        
        image:
           shana12345/microservice_3
        ports: 
            - "5002:5002"
        networks:
            - TheJesusNetwork
        deploy:
            replicas: 3

    service_4:
        
        
        image:
            shana12345/microservice_3
        ports: 
            - "5003:5003"
        networks:
            - TheJesusNetwork
        deploy:
            replicas: 3

    service_nginx:
        image: nginx:latest
        ports:
            - "80:80"
        networks:
            - TheJesusNetwork
        depends_on: 
            - service_1
            - service_2
            - service_3
            - service_4
        deploy:
            replicas: 1