---

    - hosts: manager
    
      become: true
    
      tasks:
    
        - name: deploy as stack
    
          command: docker stack deploy --compose-file docker-compose.yml stackdemo
    
          